exclude: ^(data/|app/templates/|tests/data)
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black
          - --filter-files
          - --force-grid-wrap=3

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  ## Hopefully someday
  # - repo: https://github.com/RobertCraigie/pyright-python
  #   rev: v1.1.340
  #   hooks:
  #   - id: pyright
