# Config file for automatic testing at travis-ci.org

language: python
services:
  - postgresql
  - redis-server
matrix:
    include:
      - dist: xenial
      - python: 3.6
        env: TOXENV=py36

install:
  - pip install -U tox-travis coveralls dataclasses
  - pip install -r requirements_dev.txt

before_script:
  - psql -c 'create database defaultdb;' -U postgres

script: tox

after_success:
  - coveralls
